name: main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run:  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - run: bash miniconda.sh -b -p $HOME/miniconda
      - run: 'export PATH="$HOME/miniconda/bin:$PATH"'
      - run: hash -r
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda info -a
      - run: conda update --all --yes
      - run: conda create -n testenv python='${{ matrix.python-version }}'
      - run: conda env list
      - run: source /usr/share/miniconda/etc/profile.d/conda.sh
      - run: conda activate testenv
      - run: conda install -c conda-forge r-xfun=0.27
      - run: conda install -c conda-forge r-base r-rmarkdown r-ggplot2 r-plotly pandoc
      - run: pip install pycodestyle
      - run: pip install .[all]
      - run: bash run_tests.sh
